import { describe, expect, it } from "vitest";
import { createGuardrails, generate, generateSecret, generateURI } from "otplib";
import { verifyTotpToken } from "../src/totp.js";

describe("TOTP compatibility", () => {
  it("generates authenticator-compatible secrets, URIs and valid tokens", async () => {
    const secret = generateSecret();
    const token = await generate({ secret });
    const result = await verifyTotpToken(token, secret);
    const uri = generateURI({ issuer: "Shortlinker", label: "admin@example.test", secret });

    expect(secret).toMatch(/^[A-Z2-7]+$/);
    expect(token).toMatch(/^\d{6}$/);
    expect(result).toBe(true);
    expect(uri).toMatch(/^otpauth:\/\/totp\/Shortlinker:admin%40example\.test\?/);
  });

  it("keeps 10-byte secrets generated by otplib 12 valid", async () => {
    const legacySecret = "JBSWY3DPEHPK3PXP";
    const token = await generate({ secret: legacySecret, guardrails: createGuardrails({ MIN_SECRET_BYTES: 10 }) });
    expect(await verifyTotpToken(token, legacySecret)).toBe(true);
  });
});
